import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useRef, useState } from 'react'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [messages, setMessages] = useState<string[]>([])
  const [text, setText] = useState<string>('')
  const messagesEndRef = useRef<HTMLDivElement>(null)
  
  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "auto" })
  }

  useEffect(() => {
    scrollToBottom()
  }, [messages])

  useEffect(() => {
    console.log('Component did mount')
  }, [])
  
  return (
    <div className={styles.container}>
      <Head>
        <title>EK Chatbox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          EK Chatbox
        </h1>
        <div className={styles.messageBox}>
          <div className={styles.messagesList}>
            {messages.map(msg => <div>{msg}</div>)}
            <div ref={messagesEndRef} />
          </div>
        </div>
        <form className={styles.messageBar} onSubmit={(e) => {e.preventDefault(); if (!text) return; setMessages([...messages, text]); setText("");}}>
          <input autoComplete="off" className={styles.messageInput} value={text} onChange={e => setText(e.target.value)}/>
          <button  className={styles.messageBtn}>Send</button>
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
